#  CurrentWay Message
#  Copyright (C) 2014
#  Matt Sheckells <mshecke1@jhu.edu>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


Header header
int8 wp_number
int8 properties
int8 max_speed
int16 time
int16 pos_acc
int16 chksum
int32 X
int32 Y
int32 yaw
int32 height
